### ISSUE TITLE
Error: memory access out of bounds

### ISSUE THREAD

**Issue by EvanXzj** [Emurgo/cardano-serialization-lib#151]
We use the @emurgo/cardano-serialization-lib-nodejs package to build and sign transactions, and after a while, we will get this error:

```
Error: memory access out of bounds, Stack: RuntimeError: memory access out of bounds
at alloc::vec::Vec<T>::from_raw_parts::habfae1af1b0e58b9 (wasm-function[2886]:5)
at bignum_from_str (wasm-function[1803]:23)  
at Function.from_str (/secure/signerjs-ada-1.2.0-release/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:729:24)   
at Transaction.build (/secure/signerjs-ada-1.2.0-release/node_modules/@tokens/ada/dist/transaction.js:73:46)
```

### transaction.js

```js
import * as CardanoWasm from '@emurgo/cardano-serialization-lib-nodejs';
import * as bech32 from 'bech32';


export default class Transaction {
    build(txData) {
        const {
            vin,
            vout,
            expire_block_height: ttl,
            min_fee_a: minFeeA,
            min_fee_b: minFeeB,
            min_utxo_value: minUtxoValue,
            pool_deposit: poolDeposit,
            key_deposit: keyDeposit,
            to: toAddress,
        } = txData;

        const minFeeABigNum = CardanoWasm.BigNum.from_str(minFeeA);
        const minFeeBBigNum = CardanoWasm.BigNum.from_str(minFeeB);
        const linearFee = CardanoWasm.LinearFee.new(minFeeABigNum, minFeeBBigNum);
        const minUtxoValueBigNum = CardanoWasm.BigNum.from_str(minUtxoValue);
        const poolDepositBigNum = CardanoWasm.BigNum.from_str(poolDeposit);
        const keyDepositBigNum = CardanoWasm.BigNum.from_str(keyDeposit);
        const txBuilder = CardanoWasm.TransactionBuilder.new(linearFee, minUtxoValueBigNum, poolDepositBigNum, keyDepositBigNum);

        minFeeABigNum.free();
        minFeeBBigNum.free();
        linearFee.free();
        minUtxoValueBigNum.free();
        poolDepositBigNum.free();
        keyDepositBigNum.free();

        vin.forEach(({ hash, vout_index, address, amount }) => {
            const byronAddress = CardanoWasm.ByronAddress.from_base58(address);
            const transactionHash = CardanoWasm.TransactionHash.from_bytes(Buffer.from(hash, 'hex'));
            const transactionInput = CardanoWasm.TransactionInput.new(transactionHash, vout_index);
            const amountBigNum = CardanoWasm.BigNum.from_str(amount);
            const value = CardanoWasm.Value.new(amountBigNum);

            txBuilder.add_bootstrap_input(byronAddress, transactionInput, value);

            byronAddress.free();
            transactionHash.free();
            transactionInput.free();
            amountBigNum.free();
            value.free();
        });

        this.vin = vin;

        vout.forEach(({ address, amount }) => {
            let addr;

            try {
                addr = CardanoWasm.ByronAddress.from_base58(address).to_address();
            } catch (err) {
                addr = CardanoWasm.Address.from_bech32(address);
            }

            const amountBigNum = CardanoWasm.BigNum.from_str(amount);
            const value = CardanoWasm.Value.new(amountBigNum);
            const transactionOutput = CardanoWasm.TransactionOutput.new(addr, value);
            txBuilder.add_output(transactionOutput);

            addr.free();
            amountBigNum.free();
            value.free();
            transactionOutput.free();
        });

        txBuilder.set_ttl(ttl);

        let address;
        try {
            address = CardanoWasm.ByronAddress.from_base58(toAddress).to_address();
        } catch (err) {
            address = CardanoWasm.Address.from_bech32(toAddress);
        }

        txBuilder.add_change_if_needed(address);
        address.free();

        this.txBuilder = txBuilder;

        return this;
    }


    sign(privateKeys) {
        const txBody = this.txBuilder.build();
        const txHash = CardanoWasm.hash_transaction(txBody);
        const witnesses = CardanoWasm.TransactionWitnessSet.new();

        const bootstrapWitnesses = CardanoWasm.BootstrapWitnesses.new();

        const { vin } = this;
        privateKeys.forEach((privateKey, i) => {
            const prvKey = CardanoWasm.LegacyDaedalusPrivateKey.from_bytes(
                bech32.fromWords(bech32.decode(privateKey, 1000).words),
            );

            const { address } = vin[i];
            const byronAddress = CardanoWasm.ByronAddress.from_base58(address);
            const bootstrapWitness = CardanoWasm.make_daedalus_bootstrap_witness(
                txHash,
                byronAddress,
                prvKey,
            );

            bootstrapWitnesses.add(bootstrapWitness);

            prvKey.free();
            byronAddress.free();
            bootstrapWitness.free();
        });

        witnesses.set_bootstraps(bootstrapWitnesses);

        const transaction = CardanoWasm.Transaction.new(
            txBody,
            witnesses,
            undefined, // transaction metadata
        );

        this.serialized = Buffer.from(transaction.to_bytes()).toString('hex');
        this.txHash = Buffer.from(txHash.to_bytes()).toString('hex');

        txBody.free();
        this.txBuilder.free();
        txHash.free();
        bootstrapWitnesses.free();
        witnesses.free();
        transaction.free();

        return this;
    }
}
```

Please help me find why do we encounter such a problem? Is there a problem with the code?

**Thanks!!**

**Comment by EvanXzj** [comment]
@SebastienGllmt Okay, thanks!
