### ISSUE TITLE
Deposit not returned during StakeDeregestration

### ISSUE THREAD

**Issue by trevor-crypto** [Emurgo/cardano-serialization-lib#505]
Maybe someone can help clarify if this is a bug or if I am missing something:

If you do a stake key deregistration, it seems that the initial deposit (2 ADA) is not taken into consideration in the change. It is calculated in the implicit input amount though.

Here is a test within `tx_builder.rs` I created based off of `build_tx_with_certs()`
```rust
    #[test]
    fn build_tx_with_deregistration() {
        let mut tx_builder = create_tx_builder_with_key_deposit(1_000_000);
        let spend = root_key_15()
            .derive(harden(1852))
            .derive(harden(1815))
            .derive(harden(0))
            .derive(0)
            .derive(0)
            .to_public();
        let change_key = root_key_15()
            .derive(harden(1852))
            .derive(harden(1815))
            .derive(harden(0))
            .derive(1)
            .derive(0)
            .to_public();
        let stake = root_key_15()
            .derive(harden(1852))
            .derive(harden(1815))
            .derive(harden(0))
            .derive(2)
            .derive(0)
            .to_public();

        let stake_cred = StakeCredential::from_keyhash(&stake.to_raw_key().hash());
        tx_builder.add_key_input(
            &spend.to_raw_key().hash(),
            &TransactionInput::new(&genesis_id(), 0),
            &Value::new(&to_bignum(5_000_000)),
        );
        tx_builder.set_ttl(1000);

        let mut certs = Certificates::new();
        certs.add(&Certificate::new_stake_deregistration(
            &StakeDeregistration::new(&stake_cred),
        ));
        tx_builder.set_certs(&certs);

        let change_cred = StakeCredential::from_keyhash(&change_key.to_raw_key().hash());
        let change_addr = BaseAddress::new(
            NetworkInfo::testnet().network_id(),
            &change_cred,
            &stake_cred,
        )
        .to_address();
        tx_builder.add_change_if_needed(&change_addr).unwrap();
        assert_eq!(tx_builder.min_fee().unwrap().to_str(), "182002");
        assert_eq!(tx_builder.get_fee_if_set().unwrap().to_str(), "182002");
        assert_eq!(
            tx_builder.get_implicit_input().unwrap().coin().to_str(),
            "1000000"
        ); // the stake key deposit refunded back
        assert_eq!(tx_builder.outputs.len(), 1);
        assert_eq!(
            tx_builder.get_total_input().unwrap(),
            tx_builder
                .get_total_output()
                .unwrap()
                .checked_add(&Value::new(&tx_builder.get_fee_if_set().unwrap()))
                .unwrap()
                .checked_add(&tx_builder.get_implicit_input().unwrap())
                .unwrap()
        );
        let _final_tx = tx_builder.build(); // just test that it doesn't throw
    }
```

**Comment by vsubhuman** [comment]
> ```rust
>  assert_eq!(
>             tx_builder.get_total_input().unwrap(),
>             tx_builder
>                 .get_total_output()
>                 .unwrap()
>                 .checked_add(&Value::new(&tx_builder.get_fee_if_set().unwrap()))
>                 .unwrap()
>                 .checked_add(&tx_builder.get_implicit_input().unwrap())
>                 .unwrap()
>         );
> ```

@trevor-crypto , the issue in the test is that you are additionally adding the implicit input value to the total output of the transaction, for some reason.

By the logic of the described issue you are expecting the transaction change to include the implicit input value (which it does). By that logic once you have added auto-calculated change to the transaction, the produced output value must include the implicit value so there's no need to additionally add the implicit value to the total output.

The test works correctly if that one assert is replaced with this:

```
        assert_eq!(
            tx_builder
                .get_total_input()
                .unwrap()
                .coin(),
            to_bignum(6_000_000),
        );
        assert_eq!(
            tx_builder
                .get_total_output()
                .unwrap()
                .checked_add(&Value::new(&tx_builder.get_fee_if_set().unwrap()))
                .unwrap()
                .coin(),
            to_bignum(6_000_000),
        );
```

Here we can see that `total_input = total_output + fee`, which is correct.

**Comment by trevor-crypto** [comment]
@vsubhuman ok that makes sense, thank you. For some reason when I create a transaction like this and submit it to the blockchain it tells me I am missing an input -- which was assuming meant that the deposit is not being added to the inputs:

```graphql
{
  "errors": [
    {
      "message": "Invalid Transaction",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "submitTransaction"
      ],
      "extensions": {
        "reasons": [
          {
            "name": "FeeTooSmallError",
            "details": {
              "requiredFee": 170913,
              "actualFee": 166689
            }
          },
          {
            "name": "MissingAtLeastOneInputUtxoError",
            "details": {
              "missingAtLeastOneInputUtxo": null
            }
          }
        ],
        "code": "BAD_REQUEST",
        "exception": {
          "reasons": [
            {
              "name": "FeeTooSmallError",
              "details": {
                "requiredFee": 170913,
                "actualFee": 166689
              }
            },
            {
              "name": "MissingAtLeastOneInputUtxoError",
              "details": {
                "missingAtLeastOneInputUtxo": null
              }
            }
          ],
          "stacktrace": [
            "Error: Invalid Transaction",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:69:43)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by trevor-crypto** [comment]
@vsubhuman 
> You must spend some UTxO in proper transaction inputs even if its entire value will be returned back to you in the change

I am adding inputs :disappointed:, which is why I thought that it was missing the implicit, but your explanation made it clear that I don't need to add that to the output amount manually.

Does this logic seem ok to you? :
```rust
let cfg = TransactionBuilderConfigBuilder::new()
    .fee_algo(&LinearFee::new(
        &params.fee_per_byte.into(),
        &params.fee_fixed.into(),
    ))
    .pool_deposit(&params.pool_deposit.into())
    .key_deposit(&params.key_deposit.into())
    .max_tx_size(params.max_tx_size)
    .max_value_size(params.max_val_size)
    .prefer_pure_change(true)
    .coins_per_utxo_byte(&params.coins_per_utxo_size.into())
    .build()?;
let mut tx_builder = TransactionBuilder::new(&cfg);
let mut certs = Certificates::new();
let mut inputs = TransactionUnspentOutputs::new();

let stake_credential = BaseAddress::from_address(sender)
    .ok_or_else(|| {
        anyhow!("Couldn't extract BaseAddress from Cardano account address")
    })?
    .stake_cred();
let reward_address =
    RewardAddress::new(self.network.network_id(), &stake_credential);
let stake_address = reward_address.to_address().to_bech32(None)?;

if *deregister {
    if !self.client.stake_addr_is_registered(&stake_address)? {
        bail!(
            "Stake address {} is not registered, therefore cannot deregister",
            stake_address
        );
    }

    let deregistration_cert = Certificate::new_stake_deregistration(
        &StakeDeregistration::new(&stake_credential),
    );
    certs.add(&deregistration_cert);
}

tx_builder.set_certs(&certs);

// adding inputs after everything else so the fee is correctly estimated
for utxo in utxos {
    inputs.add(&utxo);
}
tx_builder.add_inputs_from(&inputs, CoinSelectionStrategyCIP2::RandomImprove)?;
tx_builder.add_change_if_needed(sender)?;

Ok(tx_builder.build()?)
```

**Comment by vsubhuman** [comment]
> ```rust
> // adding inputs after everything else so the fee is correctly estimated
> for utxo in utxos {
>     inputs.add(&utxo);
> }
> tx_builder.add_inputs_from(&inputs, CoinSelectionStrategyCIP2::RandomImprove)?;
> ```

🤔 

@trevor-crypto , I think there actually might be an issue using this approach for this specific case of deregistering, because by the time you call this function the total input of the transaction will already include the 2 ADA from the refund, and the `.add_inputs_from` main purpose it to pick enough inputs to cover the **missing** value to cover the required total output, which is not super compatible with that specific case. The refund of the deposit itself is actually guaranteed to always be enough to cover the fees for that transaction so you can actually just take the first available UTxO and add it to the transaction directly, something like that:

```
let input = utxos[0];
tx_builder.add_input(&input,output().address(), &input.input(), &input.output().amount());
tx_builder.add_change_if_needed(sender)?;
```

**Comment by trevor-crypto** [comment]
@vsubhuman That worked! Thanks a lot for the help! 
Closing.
