### ISSUE TITLE
EnterpriseAddress::to_address Uncaught Error: null pointer passed to rust

### ISSUE THREAD

**Issue by kanzure** [Emurgo/cardano-serialization-lib#511]
```
serial = require("@emurgo/cardano-serialization-lib-nodejs");
pubkey_raw = serial.PublicKey.from_hex("f9162b91126212b71500e89dc7da31111dfc1466a9f24f48a34e7ea529d2d338");
keyhash = pubkey_raw.hash();
spend_cred = serial.StakeCredential.from_keyhash(keyhash);
network_id = serial.NetworkInfo.testnet().network_id();
entaddress = new serial.EnterpriseAddress(network_id, spend_cred);
address = entaddress.to_address(); // null pointer error occurs here
address.to_bech32();
```

traceback:
```
Uncaught Error: null pointer passed to rust
    at module.exports.__wbindgen_throw (/musk/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:19504:11)
    at wasm_bindgen::throw_str::hc6f272b899924956 (wasm://wasm/00a9ab62:wasm-function[7264]:0x1e78ac)
    at wasm_bindgen::__rt::throw_null::h66c31b20f68bfbac (wasm://wasm/00a9ab62:wasm-function[7262]:0x1e7892)
    at enterpriseaddress_to_address (wasm://wasm/00a9ab62:wasm-function[2083]:0x150f97)
    at EnterpriseAddress.to_address (/musk/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:4439:24)
```

If this is not the expected way to make an address that does not have a stake credential, then how should that be achieved?

**Comment by kanzure** [comment]
Seems to be fixed by using `.new()` per https://github.com/Emurgo/cardano-serialization-lib/issues/344#issuecomment-1036079572
