### ISSUE TITLE
i am getting this error  BlockfrostServerError:Invalid address for this network or malformed address format

### ISSUE THREAD

**Issue by ghost** [Emurgo/cardano-serialization-lib#606]
```Using address addr1q8fvgtajwpzvccdfxu5fjrmnh2rzyh46w7e5xn0yya5znvpcjn3zsax2qzsw24nppdmh78s7mknhulz8gu30tfy37flqnpr0rm
/home/hari/Documents/cardano-prac/Rosalind/node_modules/@blockfrost/blockfrost-js/lib/utils/errors.js:60
            errorInstance = new BlockfrostServerError({ ...responseBody, url });
                            ^

BlockfrostServerError: Invalid address for this network or malformed address format.
    at handleError (/home/hari/Documents/cardano-prac/Rosalind/node_modules/@blockfrost/blockfrost-js/lib/utils/errors.js:60:29)
    at /home/hari/Documents/cardano-prac/Rosalind/node_modules/@blockfrost/blockfrost-js/lib/endpoints/api/addresses/index.js:78:59
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status_code: 400,
  error: 'Bad Request',
  url: 'https://cardano-preprod.blockfrost.io/api/v0/addresses/addr1q8fvgtajwpzvccdfxu5fjrmnh2rzyh46w7e5xn0yya5znvpcjn3zsax2qzsw24nppdmh78s7mknhulz8gu30tfy37flqnpr0rm/utxos?page=8&count=100&order=asc'
}```

I am trying to send 2 ada from addr1q8fvgtajwpzvccdfxu5fjrmnh2rzyh46w7e5xn0yya5znvpcjn3zsax2qzsw24nppdmh78s7mknhulz8gu30tfy37flqnpr0rm address to addr_test1qzjeazrvkpc3twtg9xu7na0dw5zshqwwh354gmh0626gv4r9vh67k4754l9ugvw5uex30x4u6lyfvr0a34vynjmk2nzq7hqhjn address

**Comment by lisicky** [comment]
Hi @hariaccubits ! Unfortunately I don't know how the error from Blockfrom connected with the CSL without any additional context. I guess it's better to ask blockfrom about the error. But if CSL produces incorrect cbor I need a code example with explanation where CSL makes incorrect data.

**Comment by lisicky** [comment]
Not a CSL issue. I'm closing it.
